### ISSUE TITLE
Build failing under HHVM

### ISSUE THREAD

**Issue by kiler129** [php-mock/php-mock-phpunit#3] opened 2015-11-03 17:43 UTC
Is there any chance to fix serialization bug under HHVM?

**Comment by malkusch** [comment] 2015-11-03 18:29
I'll have a look in it if this could be fixed easily. But it won't help much as It breaks already in [php-mock](https://travis-ci.org/php-mock/php-mock/jobs/88585418).

**Comment by malkusch** [comment] 2015-11-03 21:56
The issue is identified. You can safely ignore this particular failing test. It comes from https://github.com/sebastianbergmann/global-state/issues/8 and might be resolved with https://github.com/sebastianbergmann/global-state/pull/3.

In this particular case it comes form the test `MockObjectProxyTest` where the mocking framework `Mockery` keeps some static attribute which some where inside has a `ReflectionMethod`. HHVM doesn't allow to serialize that `ReflectionMethod` while PHP does.

**Closed by malkusch** 2015-11-03 21:56 UTC

**Comment by kiler129** [comment] 2015-11-04 17:18
Ah, I see - you're right. Maybe you should mark these two tests as allow-fail under HHVM instead of allowing fail for entire platform? ;)
